spring:
 application:
  name: game-credit-user
 profiles:
  active: dev
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
 liquibase:
  change-log: classpath:liquibase/master.xml
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  enabled: true
eureka:
 client:
  healthcheck:
   enabled: true
mapper:
  identity: MYSQL   # 取主键的方式
  before: true      # 主键递增
  not-empty: true   # 按主键插入或更新时，是否判断字符串 != ''
  style: camelhumpandlowercase  # 实体类与表中字段的映射方式：驼峰转带下划线的小写格式
  wrap-keyword: '{0}'   # 自动配置关键字，配置后不需要使用 @Column 指定别名
  safe-delete: true   # 删除时必须设置查询条件
  safe-update: true   # 更新时必须设置查询条件
  use-java-type: true   # 是否映射Java基本数据类型
  mappers: tk.mybatis.mapper.common.Mapper
mybatis:
 mapper-locations: classpath*:mapper/**/**.xml
 type-aliases-package: com.ouyang.game.pojo.user.model
 config-location: classpath:config/mybatis_config.xml

#开启feign的熔断器功能
feign:
 hystrix:
  enabled: true
ribbon:
 OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
 ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
 MaxAutoRetries: 0     #对当前实例的重试次数，默认0
 MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1

hystrix:
 command:
  default:  #default全局有效，service id指定应用有效
   execution:
    timeout:
     #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
     enabled: true
    isolation:
     thread:
      timeoutInMilliseconds: 2000 #断路器超时时间，默认1000ms


