eureka:
 instance:
  prefer-ip-address: true
 client:
  registerWithEureka: false
  fetchRegistry: false
  prefer-ip-address: true
 server:
  enable-self-preservation: false
spring:
 application:
  name: game-credit-register
 profiles:
  active: dev

  
 
 